"""feat: add step_type to workflow_steps

Revision ID: 0b033df982b3
Revises: fc1a880b4ab3
Create Date: 2026-07-15 17:26:40.466290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b033df982b3'
down_revision: Union[str, Sequence[str], None] = 'fc1a880b4ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_steps', sa.Column('step_type', sa.String(length=50), server_default='llm', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_steps', 'step_type')
    # ### end Alembic commands ###
