"""feat_add_telegram_id_to_users

Revision ID: aed106ca2cce
Revises: 696812c633f7
Create Date: 2026-07-14 13:40:32.516401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed106ca2cce'
down_revision: Union[str, Sequence[str], None] = '696812c633f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfill: существующие строки без telegram_id получают placeholder (= id),
    # иначе SET NOT NULL упадёт. Уникальность сохраняется, т.к. id уникален.
    op.execute("UPDATE users SET telegram_id = id WHERE telegram_id IS NULL")
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
